# Generated by Django 3.2.9 on 2022-05-21 09:26

import api.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_load_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(max_length=7, validators=[api.utils.validators.model_hex_validator], verbose_name='Цвет'),
        ),
    ]
