# Generated by Django 3.2.9 on 2022-05-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_tag_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='pub_date',
            field=models.DateField(auto_now_add=True, default='2022-05-21', verbose_name='Дата добавления'),
            preserve_default=False,
        ),
    ]
