# Generated by Django 3.2.9 on 2022-05-24 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_recipe_pub_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('-pub_date',)},
        ),
    ]
