# Generated by Django 3.2.9 on 2022-05-27 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_recipe_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='recipes/images/default.jpg', upload_to='recipes/images/', verbose_name='Картинка'),
        ),
    ]
